---
title: "DAPC"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# required packages 
```{r}
library(vcfR)
library(adegenet)
library(ade4)
library(pegas)
```

# input vcf file 
```{r}
vcf<-read.vcfR("04__Genotype_Locus1_Sample_Locus2_Filtered_20perpop_imputed.vcf")
```

# genInd format
```{r}
vcf_gi<-vcfR2genlight(vcf)
```

# add groups
```{r}
group=read.table("labels_groups.txt", header=F)
colnames(group)<-c("group","genotype")
group <- group[order(group$genotype),]
group$genotype
group$group

vcf_gi$pop<- group$group
vcf_gi$pop
```

#  K-means (with BIC criteria)
```{r}
clust <- find.clusters(vcf_gi, max.n=10, scale=F, n.pca=118, parallel=F) 

```

# BIC plot
```{r}
plot(clust$Kstat, type="b", main="BIC", xlab="number of clusters (K)", ylab="BIC")
```

# DAPC using K-means result

```{r}
K <- clust$grp 
```

# DAPC with cross-validation
```{r}
xval <- xvalDapc(vcf_gi, pop(vcf_gi), n.pca.max=118, n.rep=100, parallel = "multicore", ncpus = 5)

DAPC <- dapc(vcf_gi, pop=K, n.pca=10, n.da=5, parallel=F)  
```

# DAPC Plot
```{r}
FD1 <- DAPC$ind.coord[,1]
FD2 <- DAPC$ind.coord[,2]

plot(FD1,FD2, pch=16,cex=1,col=c("deepskyblue2","olivedrab3", "darkorange","violetred4")[pop(vcf_gi)], xlab="Dicriminant axis 1", ylab=" Dicriminant axis 2")
legend(30,-5 , legend=levels(pop(vcf_gi)), pch=16,col=c("deepskyblue2","olivedrab3", "darkorange","violetred4")) 
```




