__default__:
    cpus-per-task: 1
    partition: agap_normal
    mem-per-cpu: 2G
    job-name: DC.{rule}
    output: Logs_DataCleaningWorkflow/{rule}.%j.out.txt
    error: Logs_DataCleaningWorkflow/{rule}.%j.err.txt

Demultiplex_RawFastqs:
    cpus-per-task: "{threads}"

Trimming_DemultFastqs:
    cpus-per-task: "{threads}"
    output: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.%j.out.txt
    error: Logs_DataCleaningWorkflow/{rule}.{wildcards.base}.%j.err.txt
