__default__:
    pe: smp 1
    h_vmem: 10G
    q: long.q
    N: VC.{rule}
    o: Logs_VariantCallingWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_VariantCallingWorkflow/{rule}.$JOB_ID.err.txt
   
HaplotypeCaller:
    pe: smp {threads}
    q: bigmem.q
    h_vmem: 27G
    o: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.$JOB_ID.out.txt
    e: Logs_VariantCallingWorkflow/{rule}.{wildcards.base}.$JOB_ID.err.txt

GenomicsDBImport:
    pe: smp {threads}
    q: bigmem.q
    h_vmem: 27G

Plot_GVCFVariablesHistograms:
    q: bigmem.q
    h_vmem: 50G

Plot_GVCFDPBoxplot:
    q: bigmem.q
    h_vmem: 50G
    
Plot_GVCFVariantsAlongGenome:
    q: bigmem.q
    h_vmem: 50G
