__default__:
    pe: smp 1
    q: short.q
    h_vmem: 2G
    N: VF.{rule}
    o: Logs_VcfFilteringWorkflow/{rule}.$JOB_ID.out.txt
    e: Logs_VcfFilteringWorkflow/{rule}.$JOB_ID.err.txt

Plot_FinalVCFVariablesHistograms:
    h_vmem: 4G

Plot_FinalVCFDPBoxplot:
    h_vmem: 4G
    
Plot_FinalVCFVariantsAlongGenome:
    h_vmem: 4G