name: UC-GECKO_R
channels:
  - conda-forge
  - bioconda

dependencies:
  - R-base = 4.2.2
  - r-adegenet = 2.1.10
  - r-vcfr = 1.14.0
  - r-ade4 = 1.7_22
  - r-ggplot2 = 3.4.1
  - beagle = 5.2_21Apr21.304
  - unzip = 6.0
